project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-On Exercises
        menu: 
          - text: Hands-On Exercise 1
            href: HandsOnEx1/Hands-On_Ex1.qmd
          - text: Hands-On Exercise 2
            href: HandsOnEx2/HandsOnEx2.qmd

      - text: In-Class Exercises
        menu: 
          - text: In-Class Exercise 1
            href: InClassEx1/InClassEx1.qmd
          - text: In-Class Exercise 2
            href: InClassEx2/InClassEx2.qmd

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

